CREATE TABLE USER_DETAILS( USER_LOGIN_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
                          USER_NAME VARCHAR2(50) NOT NULL,EMAIL VARCHAR2(100)NOT NULL,
                          USER_PASSWORD VARCHAR2(50)NOT NULL,MOBILE_NUMBER NUMBER NOT NULL,
                          ROLE VARCHAR2(30) DEFAULT 'USER',
                          CREATED_DATE DATE DEFAULT SYSDATE,
                          UNIQUE(EMAIL),
                          CONSTRAINT PK_USER_ID PRIMARY KEY (USER_LOGIN_ID));
                          
CREATE  TABLE ACCOUNT_DETAILS(USER_ID NUMBER  NOT NULL,ACCOUNT_NUMBER NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 112233445001 INCREMENT BY 1),
                        ACC_TYPE VARCHAR(50) NOT NULL,ACC_HOLDER_NAME VARCHAR(50),ADDRESS VARCHAR(200) NOT NULL,
                        CITY VARCHAR2(20) NOT NULL,PINCODE NUMBER,DOB DATE NOT NULL,
                        MOBILE_NUMBER NUMBER NOT NULL,
                        EMAIL VARCHAR2(100),IFSC_CODE VARCHAR2(50) NOT NULL,BRANCH_NAME VARCHAR(50) NOT NULL,BALANCE NUMBER,
                        PIN_NUMBER NUMBER NOT NULL ,ACCOUNT_STATUS VARCHAR(20),
                        CONSTRAINT PK_ACCNO PRIMARY KEY(ACCOUNT_NUMBER));
                        
                        
CREATE TABLE TRANSACTION(TRANSACTION_ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
                         SENDER_ACCOUNT_NUMBER NUMBER NOT NULL,NAME VARCHAR(50),
                         TRANSACTION_TYPE VARCHAR(50),RECEIVER_ACCOUNT_NUMBER NUMBER NOT NULL,AMOUNT NUMBER NOT NULL,
                         BALANCE NUMBER NOT NULL,TRANSACTION_STATUS VARCHAR(20),
                         TRANSACTION_DATE DATE DEFAULT SYSDATE,
                         CONSTRAINT PK_IDTRANS PRIMARY KEY(TRANSACTION_ID),
                         CONSTRAINT FK_ACCNO FOREIGN KEY(SENDER_ACCOUNT_NUMBER) REFERENCES ACCOUNT_DETAILS(ACCOUNT_NUMBER));
                         
                         


CREATE TABLE DEPOSITS(DEPOSIT_ID NUMBER  GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1), ACCOUNT_NUMBER NUMBER ,
                      USER_ID NUMBER NOT NULL,DEPOSIT_TYPE VARCHAR(30)NOT NULL,AMOUNT NUMBER NOT NULL,
                      DATE_OF_DEPOSIT DATE DEFAULT SYSDATE,TENURE number NOT NULL,RATE_OF_INTEREST NUMBER NOT NULL,
                      MATURITY_DATE DATE NOT NULL,MATURITY_VALUE NUMBER NOT NULL,
                      DEPOSIT_STATUS VARCHAR2(20) DEFAULT 'NOT APPROVED',
                      CONSTRAINT FK_RATE FOREIGN KEY (RATE_OF_INTEREST) REFERENCES  ADMIN_USE(INTEREST_RATE),
                      CONSTRAINT PK_ID PRIMARY KEY(Account_number));
                      
                      
